name: Moderate Issue
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: match_script
        with:
          result-encoding: string
          script: |
            const LOG_FILE_REGEX = /### Log File[\n \t]+\[latest.log\]\(https:\/\/github\.com\/\w+\/sodium-fabric\/files\/\d+\/latest.log\)/

            if (!LOG_FILE_REGEX.test(context.payload.issue.body)) {
                await github.rest.issues.update({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: "closed",
                  state_reason: "not_planned",
                })
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "Issue closed.",
                });
            }
