name: Moderate Issue
on:
  issues:
    types:
      - opened
jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: match_script
        with:
          result-encoding: string
          script: |
            const LOG_FILE_REGEX = "### Log File[\n \t]+\[latest.log\]\(https:\/\/github\.com\/\w+\/sodium-fabric\/files\/\d+\/latest.log\)";
            
            if (LOG_FILE_REGEX.test(context.issue.payload.body)) {
                console.log("Log file found!")
            }
