name: Moderate Issue
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: match_script
        with:
          result-encoding: string
          script: |
            const LOG_FILE_REGEX = new RegExp("### Log File[\n \t]+\[latest.log\]\(https:\/\/github\.com\/\w+\/sodium-fabric\/files\/\d+\/latest.log\)");
            console.log(context.issue.payload.body);
            
            if (LOG_FILE_REGEX.test(context.payload.issue.body)) {
                return "woo";
            }
